# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push TestFlight"
  lane :test do
      build_number = latest_testflight_build_number(api_key_path: "fastlane/Auth.json")
      build_app(scheme: "Memorize")
      upload_to_testflight(api_key_path: "fastlane/Auth.json")
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Memorize.xcodeproj"
    )
    build_app(scheme: "Memorize")
    upload_to_app_store(
      api_key_path: "fastlane/Auth.json",
      submit_for_review: true,
      automatic_release: false,
      skip_screenshots: false,
      screenshots_path: "fastlane/screenshots",
      overwrite_screenshots: false,
      precheck_include_in_app_purchases: false,
      skip_metadata: false,
      metadata_path: "metadata",
      submission_information: { add_id_info_uses_idfa: false }
    )
  end
end
